### ISSUE TITLE
Can't install Roblox Studio

### ISSUE THREAD

**Issue by maxwellcat9** [vinegarhq/vinegarhq.github.io#134] opened 2024-10-01 04:34 UTC
Whenever I try to install Roblox Studio I get an error:

Vinegar experienced an error:
failed to setup roblox: install
version-1e5deb86743148f7: setup: unhandled
package: RibbonConfig.zip

**Comment by IcansayLlanfairpwllgwyngyllgogerychwyrn** [comment] 2024-10-01 16:54
This isn't the right place for this. Please ask on the discord server, or make an issue on the vinegar repo. Also to solve the issue you need to put ```[studio]
forced_version="version-ea7c4a2d814e4dc6"``` In your config.  This is the documentation repo by the way

**Comment by apprehensions** [comment] 2024-10-01 17:05
Wrong repository, duplicate of https://github.com/vinegarhq/vinegar/issues/436

**Closed by apprehensions** 2024-10-01 17:05 UTC
